### ISSUE TITLE
[Non functional brick] GCOR brick is not working

### ISSUE THREAD

**Issue by LStruber** [populse/mia_processes#11] opened 2022-05-05 19:56 UTC
The MIA GCOR brick, created from nipype.interfaces.afni.GCOR should compute the average correlation between every voxel and ever other voxel, over any given mask, and returned this global correlation as a float number.
However when using the MIA GCOR brick, it seems to always return 0.0 and not the result of the nipype brick... 
I think there is a mistake in the way the nipype output is passed to mia output, but I have no more clue...

Note that GCOR brick is (as far as I know) the only mia brick, that is based on a nypipe process that returns a float. I think that was never tested, so it could be some sort of limitation in MIA, Capsul, ... ?

**Comment by denisri** [comment] 2022-05-10 10:35
I don't have Afni installed and I don't want to do it unless there is no other way, but we can check float output values in processes. We are actually not using them in all other processes so there might be a problem there. Values between processes (jobs, actually) should be passed by soma-workflow through json files to later jobs, but after processing he values are maybe not taken back to the client pipeline values.

**Comment by servoz** [comment] 2022-05-10 11:29
Yes, I wanted to take this ticket and that's why I decided to upgrade from casa-dev 5.0 to the latest version, 5.3-6, in order to be able to run the MRIQC pipeline that @LStruber has implemented in mia_processes. I'll take care of it as soon as I finish installing and testing this latest version of the casa-dev singularity container.

**Comment by denisri** [comment] 2022-05-10 15:19
I'm trying with a little pipeline like this one (without nipype):
```
from capsul.api import Process, Pipeline
import traits.api as traits

class P1(Process):

    def __init__(self):
        super().__init__()

        self.add_trait('output_value', traits.Float(output=True))

    def _run_process(self):
        self.output_value = 27.5

class P2(Process):

    def __init__(self):
        super().__init__()

        self.add_trait('input_value', traits.Float())
        self.add_trait('output', traits.File(output=True))

    def _run_process(self):
        with open(self.output, 'w') as f:
            f.write('output: %f\n' %self.input_value)


class PP(Pipeline):

    def pipeline_definition(self):
        self.add_process('P1', 'testbricks.P1')
        self.add_process('P2', 'testbricks.P2')

        self.add_link('P1.output_value->P2.input_value')
```
which will test if the float output value (27.5) is passed to the second process.
It runs and produces the correct output in the output file, but just when it finishes I get a segfault in mia. I think I just had time to see that the output value appears in the controller GUI before it explodes, but I can't swear it.
The message in the terminal looks like this:
```
nit time: 0.08445334434509277
- Pipeline running ...

Could not remove our own lock file "/tmp/lock_file_populse_mia.lock" maybe permissions changed meanwhile?
Could not remove our own lock file "/tmp/lock_file_populse_mia.lock" maybe permissions changed meanwhile?
set exec status on: 75cc8e98-6ac0-42a8-bb11-58a02fcec20f 2022-05-10 16:10:54
set exec status on: 14c49801-57a3-44bf-85ef-60267c66fd49 2022-05-10 16:10:55
orphan histories: {'2816e021-f6c7-4e7e-a849-e22db89bd23f'}
orphan bricks: {'14c49801-57a3-44bf-85ef-60267c66fd49', '75cc8e98-6ac0-42a8-bb11-58a02fcec20f'}
remove obsolete history: 2816e021-f6c7-4e7e-a849-e22db89bd23f
remove obsolete brick: 14c49801-57a3-44bf-85ef-60267c66fd49
remove obsolete brick: 75cc8e98-6ac0-42a8-bb11-58a02fcec20f
Fatal Python error: Segmentation fault

Thread 0x00007fc21ceec700 (most recent call first):
  File "/usr/lib/python3.6/threading.py", line 299 in wait
  File "/usr/lib/python3.6/threading.py", line 551 in wait
  File "/casa/host/build/python/soma_workflow/engine.py", line 558 in start_loop
  File "/casa/host/build/python/soma_workflow/engine.py", line 102 in run
  File "/usr/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007fc21d72d700 (most recent call first):
  File "/usr/lib/python3.6/threading.py", line 299 in wait
  File "/usr/lib/python3.6/threading.py", line 551 in wait
  File "/casa/host/build/python/soma_workflow/schedulers/local_scheduler.py", line 291 in _iterate
  File "/casa/host/build/python/soma_workflow/schedulers/local_scheduler.py", line 137 in loop
  File "/usr/lib/python3.6/threading.py", line 864 in run
  File "/usr/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007fc21df2e700 (most recent call first):
  File "/casa/host/build/python/soma_workflow/schedulers/local_scheduler.py", line 205 in poll_processes
  File "/usr/lib/python3.6/threading.py", line 864 in run
  File "/usr/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib/python3.6/threading.py", line 884 in _bootstrap

Current thread 0x00007fc2c1d8e740 (most recent call first):
  File "/casa/host/src/populse/populse_mia/master/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 2949 in close
  File "/casa/host/src/populse/populse_mia/master/python/populse_mia/main.py", line 591 in launch_mia
  File "/casa/host/src/populse/populse_mia/master/python/populse_mia/main.py", line 836 in main
  File "/casa/host/src/populse/populse_mia/master/python/populse_mia/__main__.py", line 19 in <module>
  File "/usr/lib/python3.6/runpy.py", line 85 in _run_code
  File "/usr/lib/python3.6/runpy.py", line 193 in _run_module_as_main
Segmentation fault (core dumped)
```
(I have the same reproducible crash using casa-distro image 5.0 and 5.3).
The crash only occurs if a process has an output value (float here), and happens inside Qt paint functions, so it may be a callback in a non-UI thread triggering Qt.

**Comment by LStruber** [comment] 2022-05-10 15:56
@denisri regarding MIA GCOR brick, I think that the issue is more on the side of getting back the output from nypipe process (the output float is not pasted into the controller).
If we believe that you observed the passed value in the controller, your tests would also suggest that the issue is more related to "**if and how we can retrieve a float value from a nypipe (and in this case nypipe.afni) process**".

**Comment by denisri** [comment] 2022-05-10 16:01
I haven't checked in nipype yet, and yes it might well be where the problem is. It's just that I had this crash and I'm trying to understand and fix it, but I haven't found yet.

**Comment by denisri** [comment] 2022-05-11 15:39
I cannot find out why the GUI crashes when an output value is in the pipeline. It apparently crashes if we hide/delete/close the `RunProgress` object (progress bar and worker thread), thus suggests a threading problem - maybe a callback happening in a non-GUI thread, but I checked many places and could not find one, so I'm stuck.

**Comment by denisri** [comment] 2022-05-11 16:16
I have added sync between nipype output values and capsul, which were actually lacking apparently. Thus this may solve this initial issue, and probably trigger the crash issue I mention above (which is worse, I know...)

**Comment by servoz** [comment] 2022-05-13 17:06
I just tested the GCOR process and I reproduce. the output parameter remains at the default value of the trait.

I have also just created a fake process (mia_processes.bricks.tools.Add_Floats) to test the survival of i/o processes (it's just a process that does output_float= input1_float + input2_float).

In the first test of this process, the output remains at 0.0 but input1 and input2 also return to 0.0 at the end of the run.

I haven't had time to look at the details yet, but it seems that the parameters are not saved, and when the process is instantiated during the run the user_traits are lost.

**Comment by servoz** [comment] 2022-05-13 17:22
A first quick look at the traceback seems to indicate that the input values are not found [when the process is instantiated at runtime.](https://github.com/populse/capsul/blob/master/capsul/process/process.py#L722)

**Comment by servoz** [comment] 2022-05-16 13:17
No, no, I looked too fast, the [values are well recovered just after]( https://github.com/populse/capsul/blob/master/capsul/process/process.py#L724)!

**Comment by servoz** [comment] 2022-05-16 13:58
Ugh, no and no, I made a typo in the mia_processes.bricks.tools.Add_Floats process ... I just corrected it. And now it works (we keep the input parameter values and the output parameter is fine). However, now Mia crashes just after the end of the calculation with these messages:
```
Fatal Python error: Segmentation fault

Thread 0x00007f5ba2ffd700 (most recent call first):
  File "/usr/lib64/python3.8/threading.py", line 306 in wait
  File "/usr/lib64/python3.8/threading.py", line 558 in wait
  File "/data/Git_Projects/soma-workflow/python/soma_workflow/engine.py", line 558 in start_loop
  File "/data/Git_Projects/soma-workflow/python/soma_workflow/engine.py", line 102 in run
  File "/usr/lib64/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib64/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f5ba37fe700 (most recent call first):
  File "/usr/lib64/python3.8/threading.py", line 306 in wait
  File "/usr/lib64/python3.8/threading.py", line 558 in wait
  File "/data/Git_Projects/soma-workflow/python/soma_workflow/schedulers/local_scheduler.py", line 291 in _iterate
  File "/data/Git_Projects/soma-workflow/python/soma_workflow/schedulers/local_scheduler.py", line 137 in loop
  File "/usr/lib64/python3.8/threading.py", line 870 in run
  File "/usr/lib64/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib64/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f5bb0873700 (most recent call first):
  File "/data/Git_Projects/soma-workflow/python/soma_workflow/schedulers/local_scheduler.py", line 205 in poll_processes
  File "/usr/lib64/python3.8/threading.py", line 870 in run
  File "/usr/lib64/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib64/python3.8/threading.py", line 890 in _bootstrap

Current thread 0x00007f5c34511740 (most recent call first):
  File "/data/Git_Projects/populse_mia/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py", line 2967 in end_progress
  File "main.py", line 591 in launch_mia
  File "main.py", line 836 in main
  File "main.py", line 1288 in <module>
Segmentation fault (core dumped)

```

**Comment by servoz** [comment] 2022-05-16 14:01
I think this last issue is not related to the initial problem for this ticket. So I will open a new ticket specifically for this issue.

**Comment by servoz** [comment] 2022-05-17 07:18
Observed in standard error of soma_workflow, when launching GCOR with V1 (or V2) controller display:

```
EXCEPTION: 'GCOR' object has no attribute '_gcor'

while syncing nipype parameter output_directory on GCOR

Traceback (most recent call last):

  File "/data/Git_Projects/capsul/capsul/process/nipype_process.py", line 178, in sync_process_output_traits

    nipype_outputs = (process_instance.

  File "/home/econdami/.local/lib/python3.8/site-packages/nipype-1.7.1-py3.8.egg/nipype/interfaces/afni/utils.py", line 3253, in _list_outputs

    return {"out": getattr(self, "_gcor")}

AttributeError: 'GCOR' object has no attribute '_gcor'

EXCEPTION: 'GCOR' object has no attribute '_gcor'

while syncing nipype parameter in_file on GCOR

Traceback (most recent call last):

  File "/data/Git_Projects/capsul/capsul/process/nipype_process.py", line 178, in sync_process_output_traits

    nipype_outputs = (process_instance.

  File "/home/econdami/.local/lib/python3.8/site-packages/nipype-1.7.1-py3.8.egg/nipype/interfaces/afni/utils.py", line 3253, in _list_outputs

    return {"out": getattr(self, "_gcor")}

AttributeError: 'GCOR' object has no attribute '_gcor'

EXCEPTION: 'GCOR' object has no attribute '_gcor'

while syncing nipype parameter mask on GCOR

Traceback (most recent call last):

  File "/data/Git_Projects/capsul/capsul/process/nipype_process.py", line 178, in sync_process_output_traits

    nipype_outputs = (process_instance.

  File "/home/econdami/.local/lib/python3.8/site-packages/nipype-1.7.1-py3.8.egg/nipype/interfaces/afni/utils.py", line 3253, in _list_outputs

    return {"out": getattr(self, "_gcor")}

AttributeError: 'GCOR' object has no attribute '_gcor'

EXCEPTION: 'GCOR' object has no attribute '_gcor'

while syncing nipype parameter synchronize on GCOR

Traceback (most recent call last):

  File "/data/Git_Projects/capsul/capsul/process/nipype_process.py", line 178, in sync_process_output_traits

    nipype_outputs = (process_instance.

  File "/home/econdami/.local/lib/python3.8/site-packages/nipype-1.7.1-py3.8.egg/nipype/interfaces/afni/utils.py", line 3253, in _list_outputs

    return {"out": getattr(self, "_gcor")}

AttributeError: 'GCOR' object has no attribute '_gcor'
```

**Comment by servoz** [comment] 2022-05-17 13:19
OK, I had forgotten this exception which is "normal" (well, with the current type of operation!). So the issue does not come from there!
I have just analysed capsul.process.Process.run_from_commandline() method.
- `params_conf` seems to be fine.
- in `result = ce.study_config.run(process, configuration_dict=configuration)` process and configuration seem to be fine also, the returned `result` is `None`.
- `output_param = {out:0.0}`
 It seems that the output is currently managed only if it is a file?

**Comment by servoz** [comment] 2022-05-17 13:43
Unless I'm mistaken, all our bricks/processes have values for the outputs determined at the time of initialisation. So in the capsul.process.Process.run_from_commandline() method, the process object already has good output values before the run (the run creates the "real" files already referenced in the output at the time of initialisation). So we find, indeed for files, the right values with l752 output_params[param] = getattr(process, param).
It looks like  we have not thought about the case where the output itself is the result of the calculation in the brick/process ...

**Comment by denisri** [comment] 2022-05-17 14:01
> Unless I'm mistaken, all our bricks/processes have values for the outputs determined at the time of initialisation. 

It's the way we usually use it, but it's not the only way.

> So in the capsul.process.Process.run_from_commandline() method, the process object already has good output values before the run (the run creates the "real" files already referenced in the output at the time of initialisation). So we find, indeed for files, the right values with l752 output_params[param] = getattr(process, param).

Values which are known before run are set before run, but some may not be known yet, and outputs may be changed during run. The workwlow will collect output values, and Capsul execution (client) will set back output values from the workflow after running.

> It looks like we have not thought about the case where the output itself is the result of the calculation in the brick/process ...

Actually we have... The example I have posted above (https://github.com/populse/mia_processes/issues/11#issuecomment-1122535201) illustrates it: the value of `P1.output_value` is not determined anywhere before running. The user may leave it empty, or set it to any value (which is pointless), then the execution will set it to `27.5` here. This values is passed to `P2.input_value`, and will also be set to the corresponding pipeline process nodes values after the run is finished. Except that right now, Mia crashes at that moment (populse/populse_mia#275), but the value is actually set in the GUI, we can see it changing just before the crash.

**Comment by servoz** [comment] 2022-05-17 14:25
Ok. So, in the https://github.com/populse/populse_mia/issues/275 ticket, for the V1 GUI, we only have to add in the codes the automatic update of the value at the end of the execution (actually we see a good result only if we click on the node) and for the V2 GUI we face the same problem as in this ticket which in fact is only due to the crash of Mia (which prevents of course to see the good result) ?

**Comment by denisri** [comment] 2022-05-17 15:48
The values are actually updated in the processes/pipelines, but I think the GUI v1 does not update whenever the values change, and this is where v2 crashes, because something is updated from the wrong thread (I guess). So yes for v1 you just need to update the controller GUI after the run.

**Comment by servoz** [comment] 2022-05-17 20:37
[Thanks to your code change](https://github.com/populse/populse_mia/issues/275#issuecomment-1129081721) @denisri, the GUI V2 controller does not crash Mia anymore. This is a very good thing.
But this does not fix the issue in this ticket.
The output parameter remains at the default value of the trait.
Since with the fake process everything works fine now, we can exclude a problem in the Populse machinery.
I will try to find out why the result of the nypipe process is not synchronised with the capsul process (as @LStruber  said earlier) because after these first works, it is a likely hypothesis.

**Comment by denisri** [comment] 2022-05-18 09:06
Hm, the output is not updated when the process is alone (no real pipeline). When plugs are exported, then things are updated. When the process is unconnected, the edited pipeline is non-functional, so when running, another temporary pipeline is built using the same node, connected, thus it is not the pipeline you see that is actually run. I would think the process is shared, so its modified values should also apply to the edited pipeline, but this behaviour seems to demonstrate that I'm wrong. So we have something more to do after running this single node special case.

**Comment by denisri** [comment] 2022-05-18 10:14
OK I think I have fixed it. The problem was that the workflow was keeping a weak ref to the temporary pipeline, which is not kept elsewhere thus is deleted too early. A strong ref to it is also kept in the pipeline now, and it seems to fix the issue.

**Comment by servoz** [comment] 2022-05-18 10:42
Yes, this last modification effectively fixes the last problem (which I hadn't thought of anyway!) for the [ #275](https://github.com/populse/populse_mia/issues/275) populse_mia ticket. Namely, the case of the "simple mode" brick (without exporting the input/output plugs). Indeed, thanks to this last modification the `mia_processes.bricks.tools.Add_Floats` test brick works now with or without exporting the plugs. Cool!

However, concerning the GCOR brick (this ticket), it still doesn't work, with or without the export. 
![Screenshot from 2022-05-18 12-16-03](https://user-images.githubusercontent.com/37933899/169020329-78c73ebd-446c-426c-bed0-22414c013aab.png)

I think you've solved a lot of problems we hadn't seen before, in the populse machinery, but for the GCOR brick I really think it's more a synchronisation problem between the nipype process and the capsul process. This is just a guess, of course. I'm going to look in detail at the synchronisation from nipype to populse this afternoon. Of course if you have any other ideas that I haven't seen, they are welcome!

**Comment by denisri** [comment] 2022-05-18 11:23
Well I don't have afni installed and I'm a bit too lazy (and busy) to do it right now. There was actually a sync problem in Capsul/nipype processes, outputs were not set back to the capsul process after running. I have added something to attempt to fix it (https://github.com/populse/capsul/commit/dd98b0144707733d00d145502312460576a7d2fb) but I could not test, and apparently it doesn't work.
I don't think any SPM-based nipype interface has this kind of output, so I may really have to install afni just for that, but then it will have to wait.

**Comment by servoz** [comment] 2022-05-18 11:56
No problem @denisri, you have already fixed many things!
I'll have a look on my side if I can find the reason (and the fix) for this last problem!

**Comment by denisri** [comment] 2022-05-18 15:52
I am testing using a fake process, as this one:
```
from nipype.interfaces.afni import GCOR

class FakeGCOR(GCOR):

    def _run_interface(self, runtime):
        setattr(self, "_gcor", 57.32)
        return runtime
```
Then I see that there is an error while saving the pipeline as XML.

I have fixed it.
Running this one again, which sets an output at nipype level, now actually sets the output to 57.32. I can see this number in the GUI, and in the process instance after run. Can you try using the "real" Afni when you get a moment ?

**Comment by servoz** [comment] 2022-05-18 16:06
I have just tested with capsul uptodate and unfortunately it does not change the result with the real GCOR brick...

**Comment by servoz** [comment] 2022-05-18 16:20
I'm not sure if this is a good idea or not, but after spending the afternoon introspecting capsul/nipype I noticed one thing.

The process object in capsul  (i.e in capsul/process/process.py/process.py) contains a process object which is the nipype.interfaces.afni.utils.GCOR object. In process we find `out` which remains always to `0.0` and in process.process we find well `_out` which takes well the good value (different from zero) after passing into _run_interface() of nipype/interfaces/base/core.py.

I wonder if there is a code flaw to get the right values in capsul .... It looks like that capsul take in process when the right value is in process.process ...

I continue to do introspection (it's long but it allows me to better understand the machinery!!!).

**Comment by denisri** [comment] 2022-05-18 17:44
So there would be a behaviour difference between GCOR and the derived one I used just to overload the `_run_interface()` method and bypass the actual call the the afni command ? Could you confirm that, using my fake one, things behave like for me ?

**Comment by servoz** [comment] 2022-05-18 17:52
I confirm !
![Screenshot from 2022-05-18 19-51-21](https://user-images.githubusercontent.com/37933899/169109355-5a20ba85-5113-4f4a-8db1-692aa2dbc52a.png)

**Comment by denisri** [comment] 2022-05-19 10:22
> The process object in capsul (i.e in capsul/process/process.py/process.py) contains a process object which is the nipype.interfaces.afni.utils.GCOR object.

You are takling about the nipype `Interface` object, which is `process._nipype_interface`, right ? There is no "process in the process" ?

> In process we find `out` which remains always to `0.0` and in process.process we find well `_out` which takes well the good value (different from zero) after passing into _run_interface() of nipype/interfaces/base/core.py.

The nipype Interface object parameter is named "`out`", yes. Capsul exports it as "`_out`" since it prepends an underscore to all nipype outputs in order to prevent coinflicts (nipype separates inputs and outputs, and apparently we can find the same parameter as both input and output). But then nipypes should fill in its "`out`" parameter, which is copied after execution in the "`_out`" parameter of the Capsul process. So I would understand that nipype "`out`"' was filled and capsul "`_out`" was not, if there is a bug in capsul (which was exactly the situation before the fixes a few days ago), but the situation you describe seems to be the contrary. So I don't understand.
But maybe there is something else I haven't understood in your description: you speak about "process.process" which has a parameter `_out`, and that makes no sense for me: I don't see where there is a process.process, and if it has an `_out` parameter, then it's a capsul process, not the nipype interface, so I must misunderstand something. And then I don't even know what `out` is.

**Comment by denisri** [comment] 2022-05-19 11:45
Are you sure Afni is actually working ? I have copied the whole GCOR nipype interfice to replace only its _cmd with something which runs on my machine:
```
import os
import os.path as op
import re
import numpy as np

from nipype.utils.filemanip import load_json, save_json, split_filename
from nipype.interfaces.base import (
    CommandLineInputSpec,
    CommandLine,
    Directory,
    TraitedSpec,
    traits,
    isdefined,
    File,
    InputMultiObject,
    InputMultiPath,
    Undefined,
    Str,
)
from nipype.external.due import BibTeX
from nipype.interfaces.afni.base import (
    AFNICommandBase,
    AFNICommand,
    AFNICommandInputSpec,
    AFNICommandOutputSpec,
    AFNIPythonCommandInputSpec,
    AFNIPythonCommand,
)
from nipype.interfaces.afni.utils import GCORInputSpec, GCOROutputSpec


class GCOR2(CommandLine):
    """
    Computes the average correlation between every voxel
    and ever other voxel, over any give mask.


    For complete details, see the `@compute_gcor Documentation.
    <https://afni.nimh.nih.gov/pub/dist/doc/program_help/@compute_gcor.html>`_

    Examples
    --------
    >>> from nipype.interfaces import afni
    >>> gcor = afni.GCOR()
    >>> gcor.inputs.in_file = 'structural.nii'
    >>> gcor.inputs.nfirst = 4
    >>> gcor.cmdline
    '@compute_gcor -nfirst 4 -input structural.nii'
    >>> res = gcor.run()  # doctest: +SKIP

    """

    _cmd = "echo GCOR = 45.5; #"
    input_spec = GCORInputSpec
    output_spec = GCOROutputSpec

    def _run_interface(self, runtime):
        runtime = super(GCOR2, self)._run_interface(runtime)

        gcor_line = [
            line.strip()
            for line in runtime.stdout.split("\n")
            if line.strip().startswith("GCOR = ")
        ][-1]
        setattr(self, "_gcor", float(gcor_line[len("GCOR = ") :]))
        return runtime

    def _list_outputs(self):
        return {"out": getattr(self, "_gcor")}
```
and it actually displays 45.5 at the end of execution. Now unless I forget an important thing, this `GCOR2` process is the same as the official `GCOR`, except that the commandline writes a hard-coded "`GCOR = 45`" output. thus if this one works for you (could you please try it ?), then the only difference is that the Afni commandline does not write what is expected ?

**Comment by servoz** [comment] 2022-05-19 12:26
Yes, Afni is working correctly.
I have been trying since yesterday to trace exactly what happens from mia to nipype (through all the populse machinery) and back to mia and I can see the result at the time of calculation in nipype (out = 0.0714749, with the images I take)
 It's after, at the time of synchronisation with capsul that there is a problem I think.
I try what you ask now.

**Comment by servoz** [comment] 2022-05-19 12:39
![Screenshot from 2022-05-19 14-31-44](https://user-images.githubusercontent.com/37933899/169294061-ca728288-e5e5-457d-861e-435f0f345328.png)

and the stout:
```
EXCEPTION: 'GCOR2' object has no attribute '_gcor'
while syncing nipype parameter in_file on GCOR2
Traceback (most recent call last):
  File "/data/Git_Projects/capsul/capsul/process/nipype_process.py", line 178, in sync_process_output_traits
    nipype_outputs = (process_instance.
  File "/data/Git_Projects/mia_processes/python/mia_processes/bricks/tools/test.py", line 85, in _list_outputs
    return {"out": getattr(self, "_gcor")}
AttributeError: 'GCOR2' object has no attribute '_gcor'
EXCEPTION: 'GCOR2' object has no attribute '_gcor'
while syncing nipype parameter mask on GCOR2
Traceback (most recent call last):
  File "/data/Git_Projects/capsul/capsul/process/nipype_process.py", line 178, in sync_process_output_traits
    nipype_outputs = (process_instance.
  File "/data/Git_Projects/mia_processes/python/mia_processes/bricks/tools/test.py", line 85, in _list_outputs
    return {"out": getattr(self, "_gcor")}
AttributeError: 'GCOR2' object has no attribute '_gcor'

```
But these two exceptions are usual because sync_process_output_traits() is launched for the 2 inputs in_file and mask with _list_outputs() while _gcor is only created in _run_interface().

I am currently working in the host, not in casa_distro

**Comment by servoz** [comment] 2022-05-19 12:57
no no excuse me, my bad. I made a lot of changes in the codes during the introspection and I forgot one thing! I put it back as it should be and Gcor2 works as expected... ...
![Screenshot from 2022-05-19 14-55-01](https://user-images.githubusercontent.com/37933899/169298714-e76fb6aa-0eaf-44d8-86a3-3c91f86b3fae.png)

**Comment by denisri** [comment] 2022-05-19 13:21
But it still doesn't work for the "real GCOR", is it right ?

**Comment by servoz** [comment] 2022-05-19 13:27
exactly... 
I feel like I'm going crazy... I'm starting to see the machinery pretty well but there's always something I'm missing ... arrgghhh. I'll tell you what I found, since you know the machinery in capsulus better than I do, maybe this will give you an idea...

**Comment by servoz** [comment] 2022-05-19 15:04
We pass in capsul.process.process.NipypeProcess()._run_process() at `results = self._nipype_interface.run()`: we have in self (<capsul.process.process.NipypeProcess object at 0x7f1b04b72630>) _out (Protected attribute) = 0.0383384 (the afni worked well).

then we pass throught capsul.study_config.run.run_process() : `returncode = process_instance._run_process()`, and process_instance <capsul.process.process.NipypeProcess object at 0x7f1b04b72630> have well _out = 0.0383384

then we pass throught capsul.study_config.study_config.StudyConfig.run() and process_node (<capsul.process.process.NipypeProcess object at 0x7f1b04b72630>) have well _out = 0.0383384

then capsul.process.process.Process__call__(): self (<capsul.process.process.NipypeProcess object at 0x7f1b04b72630>) _out = 0.0383384

 then capsul.process.process.Process.run(): self (<capsul.process.process.NipypeProcess object at 0x7f1b04b72630>) _out = 0.0383384

then mia_processes.bricks.reports.processes.GCOR.run_process_mia() : self (<mia_processes.bricks.reports.processes.GCOR object at 0x7f1b377688b0>) with out =0.0 and process (<capsul.process.process.NipypeProcess object at 0x7f1b04b72630>) with _out = 0.0383384

then populse_mia.user_interface.pipeline_manager.process_mia.ProcessMIA._run_process(): self (<mia_processes.bricks.reports.processes.GCOR object at 0x7f1b377688b0>) with process (<capsul.process.process.NipypeProcess object at 0x7f1b04b72630>) with _out = 0.0383384

then in capsul.study_config.run.run_process(): just after `returncode = process_instance._run_process()`, Now process_instance is not the same now <mia_processes.bricks.reports.processes.GCOR object at 0x7f1b377688b0>, we out = 0.0, and in process_instance we find process (<capsul.process.process.NipypeProcess object at 0x7f1b04b72630>) with _out = 0.0383384

then capsul.study_config.study_config.StudyConfig.run() after 
```
result, log_file = run_process(
                                      output_directory,
                                       process_node,
                                       generate_logging=self.generate_logging,
                                       verbose=verbose,
                                       configuration_dict=configuration_dict)
```

we find process_node <mia_processes.bricks.reports.processes.GCOR object at 0x7f1b377688b0> with out = 0.0 and process <capsul.process.process.NipypeProcess object at 0x7f1b04b72630> with _out = 0.0383384

then capsul.process.process.Process.run_from_commandline(): after r`esult = ce.study_config.run(process, configuration_dict=configuration)`, we have process (<mia_processes.bricks.reports.processes.GCOR object at 0x7f1b377688b0>) with out =0.0 and with process (it is process.process object) <capsul.process.process.NipypeProcess object at 0x7f1b04b72630> with _out = 0.0383384. Note here we do `output_params[param] = getattr(process, param)` with param == 'out' so we dump wrong value (0.0)



At the end of calculation if we see in populse_mia.user_interface.pipeline_manager.node_controller.NodeController.display_parameters(): we find process (<mia_processes.bricks.reports.processes.GCOR object at 0x7f45c0d1c4a0>) with out = 0.0 and with process (process.process, that's why I was talking about process.process before) 
<capsul.process.process.NipypeProcess object at 0x7f4587404c20> but not the good NipypeProcess object !=0x7f1b04b72630) and here everything is at default value. 

Anyway here it's process that is used. we didn't manage to change the value from _out to out !

**Comment by servoz** [comment] 2022-05-19 16:09
To be more clear about the pass in capsul.study_config.run.run_process():
we pass at:
`returncode = process_instance._run_process()`

- first : before `returncode = process_instance._run_process()`: process_instance <mia_processes.bricks.reports.processes.GCOR object at 0x7fdcb423eea0> process_instance.out == 0.0, process_instance.process (<capsul.process.process.NipypeProcess object at 0x7fdc820ca310>) process_instance.process._out == 0.0
we do `returncode = process_instance._run_process()`
- second: before `returncode = process_instance._run_process()`: process_instance <capsul.process.process.NipypeProcess object at 0x7fdc820ca310>  process_instance._out == 0.0
we do `returncode = process_instance._run_process()`
after `returncode = process_instance._run_process()`:
process_instance <capsul.process.process.NipypeProcess object at 0x7fdc820ca310>  process_instance._out == 0.0714749 (good value)
- end of the  first :  process_instance <mia_processes.bricks.reports.processes.GCOR object at 0x7fdcb423eea0> process_instance.out == 0.0, process_instance.process (<capsul.process.process.NipypeProcess object at 0x7fdc820ca310>) process_instance.process._out == 0.0714749
we need to take in process_instance.process for this. It is not the case

**Comment by denisri** [comment] 2022-05-19 17:26
Oh you were talking about `mia_processes.bricks.reports.processes.GCOR`, and not about `nipype.interfaces.afni.utils.GCOR` ! I was really not looking at the right place from the beginning...
I haven't looked closely how these nipype specializations (or rather embeddings) are done in Mia. It seems they are `Process`es containing another `Process`, thus I guess they should copy parameters values themselves at some point, but I haven't looked at that (yet)...

**Comment by servoz** [comment] 2022-05-19 18:35
I have just pushed [a little change on the working_in_mia_Processes#11 branch of capsul](https://github.com/populse/capsul/blob/working_in_mia_Processes%2311/capsul/process/process.py#L734) which make working the GCOR brick of mia_processes.
It's very dirty, it's just to show where there is a problem (because as it allows to make the brick working it shows where the issue is). It is obvious that we have to do better and elsewhere. But this is a first step ...

**Comment by denisri** [comment] 2022-05-20 07:16
Well I'm not familiar with `ProcessMIA` which somewhat works its own way. Here the `ProcessMIA` instance seems to wrap another `Process` instance (here the `NipypeProcess` automatically wrapping the nipype `GCOR` interface), but defines different parameter traits. The problem is that after running, the underlying `Process` outputs are not set back to the `ProcessMIA` wrapper parameters.
The wrapping in `ProcessMIA` is not known in Capsul, so I suggest you move your modification to an overload of `ProcessMIA._after_run_process()` so that it does not introduce a dependency of Capsul over Populse_mia.

Moreover the patch you are testing here assumes that any `ProcessMIA` instance has a wrapped `Process` inside, which I think is not always true (?), and that all outputs in `ProcessMIA` are mapped to an output in the wrapped process which has the same name prefixed with an underscore, which is not a general thing in `ProcessMIA` since every specialized process (like `mia_processes.bricks.reports.processes.GCOR`) declares its own traits and is theoretically free to use different names. So this would even need to be overloaded on every specialized process.

**Note:** the underscore used in `NipypeProcess` does not look very nice, I totally agree, and I guess this is what you wanted to avoid in specialized wrappers in mia_processes. I think this underscore has been introduced to avoid conflicts between input and output nipype parameters which could (theoretically) have the same name. I don't know if this actually happens in real life. The underscore was maybe not the best way, and anyway it will need to be changed in Capsul v3 since fields names cannot start with an underscore.

**Comment by servoz** [comment] 2022-05-20 07:38
Thank you for your comments. I will follow your advice, rather overloaded populse_mia side because I agree with you capsul must remain as general as possible. I have a lot of other things to deal with at the moment, I will do this ASAP (it's at the top of my todo list!).

**Closed as completed** 2022-05-20 17:24 UTC
Labels: bug

**Comment by servoz** [comment] 2022-05-21 18:01
I made some changes in this direction:
[If a nipype_process_name property is set in the trait, we use it to get the value in the process wrapped in MiaProcess.](https://github.com/populse/populse_mia/blob/master/python/populse_mia/user_interface/pipeline_manager/process_mia.py#L521)
So this solves most of the problems. [It is necessary for the brick developer to know the trait name in the wrapped process](https://github.com/populse/mia_processes/blob/mriqcPlusReport/python/mia_processes/bricks/reports/processes.py#L1671), which is the least he can do. It also allows to potentially not use the underscore anymore.
